### ISSUE TITLE
Can't create modlist

### ISSUE THREAD

**Issue by kociol21** [matortheeternal/mod-picker-issues#15]
I signed up to Mod Picker and I tried to create modlist for Skyrim Special Edition.

I created new modlist, left title and desciption defaut, imported LoadOrder txt file from NMM, set modlist visibility to 'public' and saved. It told me that list was succesfully saved. 
However when I tried to see my mods, it showed me "you are no allowed to see this modlist" 403 forbidden  message. I tried couple of times and eventually the message was gone, so was my modlist.

I did everything for second time, only this time no error. After succesfully saving my list, it is nowhere to be found. It says that I have no modlists at all.

**Comment by matortheeternal** [comment]
This is most likely because you have not allowed adult content from your account settings.  If a mod which is marked as having adult content is added to your mod list, the mod list will also be marked as having adult content.

Go to the account tab of your user settings: https://modpicker.com/skyrim#/settings/account
Check the "Allow adult content" box:
![](http://puu.sh/uc14B.png)

If you tell me your username I can verify the Mod Lists still exist on Mod Picker.

I'm planning on generating a notification when a mod list gets marked as having adult content and displaying a better error message when a user tries to access content without having allowed adult content from their user settings.

Regards,  
\- Mator

**Comment by matortheeternal** [comment]
I figured your username might be the same as here on GitHub, [found your profile](https://modpicker.com/skyrim#/user/3335), and [verified your mod list is still present](http://puu.sh/uc1pe.jpg) and is [marked as having adult content](http://puu.sh/uc1q6.png).  I will close this issue once we have improved the UX in regards to this issue.

**Comment by matortheeternal** [comment]
Issue resolved per reddit.
